apiVersion: apps/v1
kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: vignesh-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web 
    spec:
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          request:
            memory: "12Mi"
            cpu: "50m"  
        ports:
        - containerPort: 3015
